// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client-streaming/streaming-service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_CREATE EventType = 0
	EventType_UPDATE EventType = 10
	EventType_DELETE EventType = 20
)

var EventType_name = map[int32]string{
	0:  "CREATE",
	10: "UPDATE",
	20: "DELETE",
}

var EventType_value = map[string]int32{
	"CREATE": 0,
	"UPDATE": 10,
	"DELETE": 20,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6ccc0ca9e38356a5, []int{0}
}

type EventRequest struct {
	Type                 EventType `protobuf:"varint,1,opt,name=type,proto3,enum=api.EventType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccc0ca9e38356a5, []int{0}
}

func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (m *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(m, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_CREATE
}

type Event struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 EventType `protobuf:"varint,10,opt,name=type,proto3,enum=api.EventType" json:"type,omitempty"`
	Description          string    `protobuf:"bytes,20,opt,name=description,proto3" json:"description,omitempty"`
	SourceApplication    string    `protobuf:"bytes,30,opt,name=sourceApplication,proto3" json:"sourceApplication,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccc0ca9e38356a5, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_CREATE
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetSourceApplication() string {
	if m != nil {
		return m.SourceApplication
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.EventType", EventType_name, EventType_value)
	proto.RegisterType((*EventRequest)(nil), "api.EventRequest")
	proto.RegisterType((*Event)(nil), "api.Event")
}

func init() {
	proto.RegisterFile("client-streaming/streaming-service.proto", fileDescriptor_6ccc0ca9e38356a5)
}

var fileDescriptor_6ccc0ca9e38356a5 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x5f, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x4d, 0xd5, 0x42, 0x47, 0x09, 0xed, 0x52, 0xa1, 0xf8, 0x20, 0x25, 0x4f, 0x45, 0x6c,
	0xaa, 0xf1, 0x04, 0xc5, 0x2e, 0x82, 0xf8, 0x20, 0x69, 0x3c, 0x40, 0xdc, 0x0c, 0x32, 0x50, 0xb3,
	0xeb, 0xee, 0xb4, 0xd0, 0x33, 0x78, 0x69, 0xc9, 0xa8, 0x69, 0x41, 0xfa, 0xf6, 0xf1, 0xfd, 0x61,
	0x98, 0x1f, 0x4c, 0xcc, 0x8a, 0xb0, 0xe6, 0x69, 0x60, 0x8f, 0xe5, 0x07, 0xd5, 0xef, 0xb3, 0x56,
	0x4d, 0x03, 0xfa, 0x0d, 0x19, 0x4c, 0x9d, 0xb7, 0x6c, 0xd5, 0x71, 0xe9, 0x28, 0xc9, 0xe0, 0x5c,
	0x6f, 0xb0, 0xe6, 0x1c, 0x3f, 0xd7, 0x18, 0x58, 0x25, 0x70, 0xc2, 0x5b, 0x87, 0xa3, 0x68, 0x1c,
	0x4d, 0xe2, 0x2c, 0x4e, 0x4b, 0x47, 0xa9, 0x14, 0x8a, 0xad, 0xc3, 0x5c, 0xb2, 0xe4, 0x2b, 0x82,
	0x53, 0xf1, 0x54, 0x0c, 0x1d, 0xaa, 0xa4, 0xdb, 0xcb, 0x3b, 0x54, 0xb5, 0x6b, 0x38, 0xbc, 0x56,
	0x63, 0x38, 0xab, 0x30, 0x18, 0x4f, 0x8e, 0xc9, 0xd6, 0xa3, 0xa1, 0x8c, 0xf7, 0x2d, 0x75, 0x03,
	0x83, 0x60, 0xd7, 0xde, 0xe0, 0xdc, 0xb9, 0x15, 0x99, 0x52, 0x7a, 0x57, 0xd2, 0xfb, 0x1f, 0x5c,
	0xcf, 0xa0, 0xd7, 0x9e, 0x50, 0x00, 0xdd, 0x87, 0x5c, 0xcf, 0x0b, 0xdd, 0x3f, 0x6a, 0xf4, 0xeb,
	0xcb, 0xa2, 0xd1, 0xd0, 0xe8, 0x85, 0x7e, 0xd6, 0x85, 0xee, 0x0f, 0xb3, 0x27, 0xb8, 0x90, 0xc1,
	0xf2, 0x8f, 0xcb, 0xf2, 0x07, 0x8b, 0xba, 0x83, 0xf8, 0x11, 0x79, 0x2f, 0x53, 0x83, 0xdd, 0x07,
	0xbf, 0x80, 0x2e, 0x61, 0x67, 0xdd, 0x46, 0x6f, 0x5d, 0x41, 0x79, 0xff, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x74, 0xc9, 0x08, 0x60, 0x76, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventStreamingServiceClient is the client API for EventStreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventStreamingServiceClient interface {
	GetEventStream(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (EventStreamingService_GetEventStreamClient, error)
}

type eventStreamingServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventStreamingServiceClient(cc *grpc.ClientConn) EventStreamingServiceClient {
	return &eventStreamingServiceClient{cc}
}

func (c *eventStreamingServiceClient) GetEventStream(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (EventStreamingService_GetEventStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EventStreamingService_serviceDesc.Streams[0], "/api.EventStreamingService/GetEventStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventStreamingServiceGetEventStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EventStreamingService_GetEventStreamClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type eventStreamingServiceGetEventStreamClient struct {
	grpc.ClientStream
}

func (x *eventStreamingServiceGetEventStreamClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EventStreamingServiceServer is the server API for EventStreamingService service.
type EventStreamingServiceServer interface {
	GetEventStream(*EventRequest, EventStreamingService_GetEventStreamServer) error
}

// UnimplementedEventStreamingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventStreamingServiceServer struct {
}

func (*UnimplementedEventStreamingServiceServer) GetEventStream(req *EventRequest, srv EventStreamingService_GetEventStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEventStream not implemented")
}

func RegisterEventStreamingServiceServer(s *grpc.Server, srv EventStreamingServiceServer) {
	s.RegisterService(&_EventStreamingService_serviceDesc, srv)
}

func _EventStreamingService_GetEventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStreamingServiceServer).GetEventStream(m, &eventStreamingServiceGetEventStreamServer{stream})
}

type EventStreamingService_GetEventStreamServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type eventStreamingServiceGetEventStreamServer struct {
	grpc.ServerStream
}

func (x *eventStreamingServiceGetEventStreamServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _EventStreamingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.EventStreamingService",
	HandlerType: (*EventStreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEventStream",
			Handler:       _EventStreamingService_GetEventStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "client-streaming/streaming-service.proto",
}
